# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_missing_dots <- function(env) {
    .Call(`_filearray_check_missing_dots`, env)
}

set_buffer_size <- function(size) {
    .Call(`_filearray_set_buffer_size`, size)
}

get_buffer_size <- function() {
    .Call(`_filearray_get_buffer_size`)
}

kinda_sorted <- function(idx, min_, buffer_count) {
    .Call(`_filearray_kinda_sorted`, idx, min_, buffer_count)
}

realToUint64 <- function(x, min_, max_, strict) {
    .Call(`_filearray_realToUint64`, x, min_, max_, strict)
}

locationList <- function(listOrEnv, dim, strict) {
    .Call(`_filearray_locationList`, listOrEnv, dim, strict)
}

reshape_or_drop <- function(x, reshape, drop) {
    .Call(`_filearray_reshape_or_drop`, x, reshape, drop)
}

loc2idx <- function(sliceIdx, dim) {
    .Call(`_filearray_loc2idx`, sliceIdx, dim)
}

schedule <- function(listOrEnv, dim, cum_part_sizes, split_dim, strict) {
    .Call(`_filearray_schedule`, listOrEnv, dim, cum_part_sizes, split_dim, strict)
}

FARR_subset <- function(filebase, type, listOrEnv, dim, cum_part_sizes, split_dim, reshape = NULL, drop = FALSE, strict = 1L) {
    .Call(`_filearray_FARR_subset`, filebase, type, listOrEnv, dim, cum_part_sizes, split_dim, reshape, drop, strict)
}

FARR_buffer_mapreduce <- function(filebase, map, reduce, dim, partition_cumlens, bufferlen, x_type) {
    .Call(`_filearray_FARR_buffer_mapreduce`, filebase, map, reduce, dim, partition_cumlens, bufferlen, x_type)
}

getThreads <- function(max = FALSE) {
    .Call(`_filearray_getThreads`, max)
}

setThreads <- function(n, reset_after_fork = -1L) {
    .Call(`_filearray_setThreads`, n, reset_after_fork)
}

hasOpenMP <- function() {
    .Call(`_filearray_hasOpenMP`)
}

FARR_subset_assign_integer <- function(filebase, sch, value) {
    .Call(`_filearray_FARR_subset_assign_integer`, filebase, sch, value)
}

FARR_subset_assign_double <- function(filebase, sch, value) {
    .Call(`_filearray_FARR_subset_assign_double`, filebase, sch, value)
}

FARR_subset_assign_raw <- function(filebase, sch, value) {
    .Call(`_filearray_FARR_subset_assign_raw`, filebase, sch, value)
}

FARR_subset_assign_logical <- function(filebase, sch, value) {
    .Call(`_filearray_FARR_subset_assign_logical`, filebase, sch, value)
}

FARR_subset_assign <- function(filebase, listOrEnv, dim, cum_part_sizes, split_dim, type, value_) {
    .Call(`_filearray_FARR_subset_assign`, filebase, listOrEnv, dim, cum_part_sizes, split_dim, type, value_)
}

